In [5]:
import numpy as np

In [6]:
a = [1,2,3,]
a
print(type(a))

<class 'list'>


In [7]:
np.array(a)


array([1, 2, 3])

In [8]:
type(a)

list

In [10]:
matrix = [[1,2],[3,4]]
y = np.array(matrix)
print(y)
type(y)

[[1 2]
 [3 4]]


numpy.ndarray

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [27]:
np.random.rand(2)

array([0.21190341, 0.22361987])

In [28]:
np.random.rand(5) #0 sampai 1 

array([0.03028285, 0.52201496, 0.17891207, 0.28396066, 0.95546489])

In [30]:
np.random.rand(5,5)

array([[0.9228207 , 0.68527715, 0.37262274, 0.72747737, 0.68767685],
       [0.24676472, 0.41458574, 0.74658109, 0.31495564, 0.87901577],
       [0.2364789 , 0.49078984, 0.24756525, 0.9675196 , 0.56525591],
       [0.23584129, 0.10954288, 0.91687936, 0.32573765, 0.27870995],
       [0.43775778, 0.76537265, 0.06613846, 0.12401937, 0.76110751]])

In [31]:
np.random.randn(5)

array([ 0.63524708,  0.15800573,  0.65410143, -0.36022758,  0.70570143])

In [32]:
np.random.randn(5,5)

array([[-1.11645037,  1.22801794,  0.28871068,  0.43969244,  0.39329284],
       [-1.53371268,  0.71732775,  0.81530986,  0.03000559, -1.55146999],
       [-1.10984315, -0.11826067,  1.01078238,  1.91978171,  0.07400434],
       [-1.71370898,  0.0381347 ,  0.64855181,  0.11764378, -0.10630514],
       [ 1.79715564,  0.4373905 , -0.11443249, -2.26922261, -0.3906739 ]])

In [33]:
np.random.randint(1,100)

55

In [37]:
np.random.randint(1,100,10)

array([31, 84, 54, 49, 68, 97, 76, 27, 30, 90])

In [39]:
x = np.random.randint(0,10,5)
x

array([6, 1, 8, 3, 1])

In [40]:
x.shape

(5,)

In [42]:
y = np.random.randn(5,5)
y.shape

(5, 5)

In [52]:
z = np.linspace(0,20,30)
z

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [61]:
z.reshape(2,5,3)

array([[[ 0.        ,  0.68965517,  1.37931034],
        [ 2.06896552,  2.75862069,  3.44827586],
        [ 4.13793103,  4.82758621,  5.51724138],
        [ 6.20689655,  6.89655172,  7.5862069 ],
        [ 8.27586207,  8.96551724,  9.65517241]],

       [[10.34482759, 11.03448276, 11.72413793],
        [12.4137931 , 13.10344828, 13.79310345],
        [14.48275862, 15.17241379, 15.86206897],
        [16.55172414, 17.24137931, 17.93103448],
        [18.62068966, 19.31034483, 20.        ]]])

In [62]:
a = np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
z = np.linspace(0,20,30)
z

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [69]:
z.reshape(30,1)

array([[ 0.        ],
       [ 0.68965517],
       [ 1.37931034],
       [ 2.06896552],
       [ 2.75862069],
       [ 3.44827586],
       [ 4.13793103],
       [ 4.82758621],
       [ 5.51724138],
       [ 6.20689655],
       [ 6.89655172],
       [ 7.5862069 ],
       [ 8.27586207],
       [ 8.96551724],
       [ 9.65517241],
       [10.34482759],
       [11.03448276],
       [11.72413793],
       [12.4137931 ],
       [13.10344828],
       [13.79310345],
       [14.48275862],
       [15.17241379],
       [15.86206897],
       [16.55172414],
       [17.24137931],
       [17.93103448],
       [18.62068966],
       [19.31034483],
       [20.        ]])

In [70]:
z.reshape(-1)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [71]:
z.reshape(-1).shape

(30,)

In [86]:
b = np.random.randint(0,100,10)
b

array([98, 63, 96, 99, 10, 44, 13, 72, 38, 14])

In [87]:
b.max()

99

In [88]:
b.argmax()

3

In [89]:
b.min()

10

In [91]:
b.argmin()

4

In [3]:
import numpy as np
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a[2]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a[-2:]

array([ 9, 10])

In [9]:
a[0:10:2]

array([0, 2, 4, 6, 8])

In [11]:
a[0:2] = 3
a

array([ 3,  3,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a.dtype

dtype('int32')

In [14]:
b = np.linspace(0,10,10)
b.dtype

dtype('float64')

In [15]:
test = np.arange(0,11)
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
test = np.arange(0,11)
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
slicedTest = test[0:6]
slicedTest

array([0, 1, 2, 3, 4, 5])

In [27]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
test2nd = np.array(([5,10,15],[20,25,30],[35,40,45]))
test2nd 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
test2nd[1]

array([20, 25, 30])

In [36]:
test2nd[2][1]

40

In [37]:
test2nd[2,1]

40

In [38]:
test2nd = np.array(([5,10,15],[20,25,30],[35,40,45]))
test2nd

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
test2ndSliced = test2nd[:2,1:]
test2ndSliced

array([[10, 15],
       [25, 30]])

In [45]:
test2ndSliced2 = test2nd[:1,]
test2ndSliced2

array([[ 5, 10, 15]])

In [46]:
#fancy indexing
test = np.arange(0,11)
test[[1,2,3]]

array([1, 2, 3])

In [47]:
test2nd

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
test2nd[[0,1]]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [50]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
test>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [52]:
boolTest = test>4
boolTest

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [53]:
test[boolTest]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
test[test>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
x = 2 
test[test>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])